apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
  namespace: istio-system
  labels:
    app: grafana
    service: grafana
spec:
  type: NodePort
  ports:
    - port: 3000
      name: http
      nodePort: 32300
  selector:
    app: grafana
