apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress
  namespace: chaos-testing
spec:
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: scaffold-a
  stressors:
    cpu:
      workers: 1
      load: 80
  #duration: '30s'
  #scheduler:
  #  cron: '@every 1m'
