apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-stress
  namespace: chaos-testing
spec:
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: scaffold-a
  stressors:
    memory:
      workers: 1
      size: 500m
  #duration: '30s'
  #scheduler:
  #  cron: '@every 1m'
