apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: container-kill-example
  namespace: chaos-testing
spec:
  action: container-kill
  mode: one
  containerName: 'scaffold'
  selector:
    namespaces:
      - default
    labelSelectors:
      'app': 'scaffold-a'
  scheduler:
    cron: '@every 30s'
