apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-duplicate-example
  namespace: chaos-testing
spec:
  action: duplicate
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      "app": "scaffold-a"
  duplicate:
    duplicate: "100"
    correlation: "100"
  #duration: "10s"
  #scheduler:
  #  cron: "@every 15s"
