apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-loss-example
  namespace: chaos-testing
spec:
  action: loss
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      "app": "scaffold-a"
  loss:
    loss: "100"
    correlation: "100"
  duration: "10s"
  scheduler:
    cron: '@every 10s'
