apiVersion: chaos-mesh.org/v1alpha1
kind: IoChaos
metadata:
  name: io-delay-example
spec:
  action: latency
  delay: 5000ms
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: scaffold-a
  volumePath: /tmp/scaffold/
  path: ''
  percent: 100
  duration: '10s'
  scheduler:
    cron: '@every 30s'
